#!/bin/zsh

# define
this_script=`basename $0`
docker_volume='aws-credentials'
docker_container='aws-tmp'
docker_mount_path='/aws-volume'
tmp_cred_filename='aws-credentials'
tmp_cred_file="/tmp/${tmp_cred_filename}"

# clear temporary credentisla file
: > $tmp_cred_file

# copy credentals file to docker volume
docker run -d --rm --name $docker_container --mount type=volume,source=${docker_volume},target=${docker_mount_path} amazon/aws-cli > /dev/null
docker cp ${tmp_cred_file} ${docker_container}:${docker_mount_path}/credentials > /dev/null
docker stop $docker_container > /dev/null

# remove temporary credentials file from local
rm -f $tmp_cred_file
echo 'credentials file cleared'