on:
  push:
    branches:
      - 'feature/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  make:
    runs-on: macos-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dotfiles
        run: |
          MAS_APPS="$(cat home/.Brewfile | grep -v brew | grep mas | sed 's/^.*id: \(.*\) *$/\1/' | tr '\n' ' ')"
          export HOMEBREW_BUNDLE_MAS_SKIP="$MAS_APPS"
          make
